ALTER TABLE "RequestLog"
ADD COLUMN "memoryDeltaMb" DOUBLE PRECISION,
ADD COLUMN "ioBytes" DOUBLE PRECISION,
ADD COLUMN "networkBytes" DOUBLE PRECISION,
ADD COLUMN "provider" TEXT,
ADD COLUMN "region" TEXT;
